### ISSUE TITLE
Default 'download' command fails for Windows

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#23]
After fresh installs of git, Strawberry Perl and rakubrew, entering 'rakubrew download' gives me:

`Couldn't find a precomp release for OS: "win", architecture: "x86_64"`

I got this response on three machines (virtual Win7 and Win10, and one 'real' Win10).   I saw that antoniogamiz had this same issue in June, but it isn't clear to me how it got resolved. 

- What's the output of `rakubrew rakubrew-version`?:
   rakubrew v9 Build type: win OS: MSWin32
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
    shim
- Where is rakubrew installed? (run `rakubrew home` to find out):  
    C:/rakubrew

**Comment by patrickbkr** [comment]
Thanks for reporting this!

I'm pretty sure this is a duplicate of #14 which was fixed and released as version 12. That release is not uploaded to the website yet though. That's why you are currently not able to update to that newer release.

I'll try to see what I can do to get the newer releases uploaded.

Sorry for that!

**Comment by SqrtNegInf** [comment]
Right, built v13 from the git archive, now `rakubrew download` successfully fetches `moar-2020.08.2`.  

Still can't get moar-blead (as per other issue, MoarVM problem), but hopefully that all gets straightened out next week.
