### ISSUE TITLE
Whitespace in path name on MacOS, while building 3rd-party/dyncall

### ISSUE THREAD

**Issue by SqrtNegInf** [Raku/App-Rakubrew#4]
The whitespace in directory name 'Application Support' needs to be escaped/quoted in the makefile for 'dyncall'.

```
% rakubrew build moar-blead

building dyncall...
./configure: line 261: cd: /Users/dhoekman/Library/Application: No such file or directory
usage: dirname path
usage: dirname path
mkdir: : No such file or directory
./configure: line 268: /Makefile: Permission denied
```

At line 23 of 'configure', setting SRCTOP to the full path necessarily includes 'Application Support', and it's embedded whitespace.  This will affect all versions of MacOS.

**Comment by SqrtNegInf** [comment]
More whitespace woes... I patched the above problem, tried to continue with the build process, but soon stalled out again in 3rdparty/libatomicops:

```
configure:3275: clang -fno-omit-frame-pointer -fno-optimize-sibling-calls -O3 -DNDEBUG -Wno-logical-op-parentheses -D_DARWIN_USE_64_BIT_INODE=1  -DMVM_HEAPSNAPSHOT_FORMAT=2 -DMVM_TRACING=0 -DMVM_CGOTO=1 -DMVM_RDTSCP=0  -O3 -DNDEBUG -Wl,-rpath,"//Users/dhoekman/Library/Application Support/.rakubrew/versions/moar-blead/install/lib" conftest.c  >&5
clang: error: no such file or directory: 'Support/.rakubrew/versions/moar-blead/install/lib"'
configure:3279: $? = 1
configure:3317: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libatomic_ops"
| #define PACKAGE_TARNAME "libatomic_ops"
| #define PACKAGE_VERSION "7.3alpha3"
```

I have been using rakudobrew system successfully, so have to wonder if changing the build location to 'Application Support' is just going to be an on-going headache?

**Comment by patrickbkr** [comment]
Thanks for the report!
These are basically bugs in the build process of Rakudo, NQP and MoarVM. I know for sure Rakudo is able to _run_ in a path that has spaces and unicode characters in it. Obviously the build process still struggles with those.
Fixing this is non trivial.
I don't own a Mac, so have little knowledge. Is this `Application Support` folder the default folder for application specific data? If yes, I should probably make sure rakubrew installs somewhere else until we manage to fix the Rakudo build process.

**Comment by SqrtNegInf** [comment]
I would avoid the MacOS-specific locations ('~/Library/Application Support' and '~/Applications' and '/Applications') and use the defaults you would for Linux/Unix (Darwin is just a variation on BSD UNIX after all).

**Comment by patrickbkr** [comment]
The problem turns out to be bigger than I hoped. On Windows rakubrew installs to `C:\Users\John Doe\AppData\local\rakubrew`. That folder also has a space in many cases (whenever the user gave his first and last name on account creation). So we'll need a solution for this situation as well.
I pondered building in a temporary folder (`$TMPDIR` on MacOS has no spaces, neither does `/tmp` on Linux), but on Windows the temp folder is usually in the users dir as well, so nothing is won.
Then again making Rakudo build in a path with spaces (and unicode characters) is doable, but not trivial.
I haven't yet decided how to proceed.

In the meantime you can set a different installation location by specifying `export RAKUBREW_HOME=/some/other/folder/without/a/space/rakubrew` before loading rakubrew in `~/.bashrc`.

**Comment by patrickbkr** [comment]
I have given up on trying to be clever with the spaces in path problem. There are some very difficult hurdles to overcome to get this done cleanly. So rakubrew (in the recently released version 5) now defaults to installing to ~/.rakubrew and C:\rakubrew and warns during install when the install dir contains a space. I hope this solves this problem as good as is possible given the circumstances we have.
@SqrtNegInf Thanks for all the testing and pointers!
