### ISSUE TITLE
Missing support for Macs with M chip aarch64

### ISSUE THREAD

**Issue by kwolcott** [Raku/App-Rakubrew#77]
- What's the output of `rakubrew rakubrew-version`?:
- Are you using rakubrew in `env` or in `shim` mode? (run `rakubrew mode` to find out):
- Where is rakubrew installed? (run `rakubrew home` to find out):

was able to run the initial curl command.  After that, most things were wacky.

rakubrew download

Use of uninitialized value in pattern match (m//) at /var/folders/w6/y2gky19s1mbcg5cgwj4512q40000gn/T/par-6b776f6c636f7474/cache-ca652fcef33b0ea11866711f8942456fa9e17297/inc/lib/App/Rakubrew/Download.pm line 149.

Couldn't detect system architecture. Current arch is: darwin-2level
Current uname -a is: Darwin Mac-mini.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 x86_64

**Comment by raiph** [comment]
What happens when you try running this command on your system?:
```
sysctl -n machdep.cpu.brand_string
```
My guess is you get something like a command not found. Or, perhaps more likely, some error.

So, do you know anything about what `sysctl` is? Do you know why it would not be found or would raise an error for that command? Can you try enable things so it will work? Or figure out a patch for the relevant code (see below) that might work? Any other ideas?

----

Here's my rational for my questions:

I know pretty much nothing about sysadmin, Macs, or rakubrew. But I know Raku, and a smidgen of Perl, and happened to read this issue.

I just went and looked at the Perl module that was mentioned in the warning message about an uninitialized value.

The line mentioned is part of a long series of pattern matches. The only two lines that can possibly emit that warning are:
```
$Config{archname} =~ /darwin/i && `sysctl -n machdep.cpu.brand_string` =~ /Apple/i ? 'arm64'  : # MacOS M1 / Apple Silicon
$Config{archname} =~ /darwin/i && `sysctl -n machdep.cpu.brand_string` =~ /Intel/i ? 'x86_64' : # MacOS Intel
```
This of course makes some sense given that this problem is Mac related, and the final error ("Couldn't detect system architecture") would be a natural consequence of these pattern matches failing to identify the arch.

The bit that I think has the potential to yield an uninitialized value in pattern match warning is the two `sysctl ...` bits. This is Perl's syntax for executing a command on a system (via the default shell I think, but don't, er, quote me on that).

At first I was surprised that (I thought) you only got one warning, not two. But it just dawned on me you probably got both but they were exactly the same thing repeated twice.

**Comment by colomon** [comment]
Quick answer for my M1 laptop:

```
    % sysctl -n machdep.cpu.brand_string
    Apple M1 Max
```

I don't remember exactly what happened when I set up this machine, but I'm running rakubrew on my Linux machines and not on my M1 Macs.

**Comment by kwolcott** [comment]
HI;

sysctl -n machdep.cpu.brand_string
zsh: command not found: sysctl

Going a google search I see that the full path should be /sbin/sysctl.
/sbin is in my path
However, sysctl is not in /sbin
I'm running Ventura 13.5.1

So, my MacOS installation is not complete?

Thanks,
Ken

**Comment by kwolcott** [comment]
Another google search clues me in that some MacOS installations have placed the sysctl command in /usr/sbin, and yes, it is there, and no, it is not in my path.  So I will add that to my path and try again.

**Comment by colomon** [comment]
Is it possible this has something to do with whether or not Xcode is installed?

**Comment by patrickbkr** [comment]
I have added code to try harder to find sysctl. This should hopefully help with such cases in the future. See https://github.com/Raku/App-Rakubrew/commit/bab182828e8bcfb8f7b6be9dafdc2c67027f9973
